### ISSUE TITLE
데이터 저장소변경 (localstorage to SQLLite or Something)

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1514]
기존에 localstorage에 저장하는 데이터를 내장으로 바꾸어야 함.

https://gonehybrid.com/dont-assume-localstorage-will-always-work-in-your-hybrid-app/
https://www.sitepoint.com/storing-local-data-in-a-cordova-app/

**Comment by kimalec** [comment]
처음 실행시 localStorage 내용을 신규 저장소에 저장해야 함.
동일한 항목에 대하여 신규 저장소에 데이터가 있다면 무시함.

새롭게 저장하는 데이터는 모두 신규 저장소에 저장함.

**Comment by skywlrl** [comment]
아래와 같은 고려사항이 있어 holding함(현재까지 진행한 코드는 pr하여 올려둠)
**localStorage를 사용하는 부분을 전부 appPreference로 변경하는 것은 무리임!!**
- 비동기 처리에 의한 응답 속도 느린 문제 발생
-> start page, deep link 실행 시 appPreference에서 데이터 가져온 후에 처리하도록 지연 처리를 해야 함
- 기본적으로 localStorage를 사용하나 backup의 용도로 appPreference를 사용하는 방법 검토 필요
-> 실행 시 appPreference를 localStorage로 backup 하는 경우 backup 진행 상태를 progressbar로 표시하는 방법이나 app.run을 backup 완료 후에 처리되도록 고려해야 함. 
- 각각의 데이터를 하나의 object로 묶어서 한번 read, write로 appPreference에 접근하는 방법 검토 필요
-> read는 앱 실행 시 메모리로 로드하여 Controller, Service에서는 sync로 접근해서 사용
-> write는 로드된 메모리를 변경하면 async로 storage에 저장

**Comment by kimalec** [comment]
#1639 merge 안하고, keep해둠 추후 검토시 참고해야함.

**Comment by skywlrl** [comment]
**[수정 내용]**
guide의 title 제거
start 페이지 표시 전에 HeaderBar가 잠깐 보이는 문제 수정
* $stateChangeStart에서 start에 대해 viewColor와 headerbar를 흰색으로 설정
불필요한 run 제거
1. service.run.js 제거 : 코드는 app.run으로 이동
    * WeatherInfo.loadCities()는 TwStorage.init() 이후에 하도록 시점 이동
2. service.push의 run 제거 : factory의 init()으로 변경, app.run에서 push.init() 호출
3. controller.purchase의 run 제거 : factory의 init() 함수 추가, app.run에서 purchase.init() 호출
    * controller.purchase.j3k0의 run 제거
    * controller.purchase.alexdisler의 run 제거 : factory의 init()으로 변경
시작 시점 변경
1. $urlRouterProvider.otherwise 제거 : TwStorage.init() 이후에 직접 location 이동
2. $stateChangeStart에서 tab.forecast일 때 start 페이지 이동하는 코드 제거 : TwStorage.init() 이후에 startVersion 확인 후 location 이동
Util.saveServiceKeys() 처리 코드 위치 변경
* Util과 TwStorage에서 서로 injection을 하면서 에러가 발생하므로 app.js에서 사용하는 부분에서 직접 해당 코드 사용하도록 함

service.storage 추가
1. appPreference의 suiteName은 "group.net.wizardfactory.todayweather”으로 통일
2. 모든 data는 TwStorage를 통해서 get/set 하도록 변경
    * data는 object 형태로 get에서 JSON.parse, set에서 JSON.stringify로 처리
    * cityIndex, startVersion은 기존처럼 object가 아닌 string으로 처리
3. init에서 하위호환 및 localStorage와 appPreference의 data 업데이트
    - localStorage가 clear 된 경우 appPreference의 data를 localStorage로 update
    - appPreference에 저장하는 data를 localStorage로 업데이트, android는 suiteName 변경하여 재저장 처리
        * controller.purchase.j3k0의 purchaseInfo, controller.units의 units, service.weatherinfo의 cityList, service.util의 daumServiceKeys를 TwStorage get/set으로 처리
    - localStorage에 저장하는 data는 appPreference로 업데이트
        * service.twads의 twAdsInfo, service.push의 pushData, controller.purchase.alexdisler의 purchaseInfo/storeReceipt, service.weatherinfo의 cities/cityIndex, controller.start의 startVersion을 TwStorage get/set으로 처리
        * controller.settingctrl의 startupPage/refreshInterval은 settingsInfo로 TwStorage get/set 처리,  최초 실행 시 default 값으로 설정
    - localStorage의 하위 호환 처리
        * startVersion를 guideVersion으로 설정
        * controller.settingctrl의 startupPage/refreshInterval은 settingsInfo로 된 object 형태로 변환

**Comment by kimalec** [comment]
- [ ] android widget에서 suiteName 변경된 부분 맞추기, 기존 저장 데이터들 문제 없는지 확인 (필요시 하위호환코드 추가)
- [ ] current position native와 share
- [ ] iOS 동작 이상확인

Test case
- [ ] 이전 버전에서 현재버전 넘어오는 케이스
- [ ] 새로 사용시 오동작 케이스
- [ ] localStorage데이터가 로스는 경우 복구 케이스

**Comment by kimalec** [comment]
용량 부족시에 동작확인했음.
