### ISSUE TITLE
android widget 개선

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#423]
#241 에서 작업 내용에 추가 개선으로 android에서 widget가 시안대로 나오도록 개선하기.

<img width='240' src='https://cloud.githubusercontent.com/assets/12652131/10867309/3a9fe594-809e-11e5-84ed-a7231345a0c1.png'>

**Comment by skywlrl** [comment]
* 위젯을 RESIZE_NONE으로 설정해도 크기가 변하는 이유 : 삼성 단말의 경우 무시한다고 함
Android 4.x also allows widget re-sizing with a public and official API.
For some reason with the official Samsung ICS update the Touchwiz launcher only allow resizing of Samsung's own widgets.
For 3rd party widgets it completely ignores the android:resizeMode, android:minResizeHeight and android:minResizeWidth parameters.
Assuming it is by design and not a bug, I can't understand why Samsung thinks its OK ignore official SDK features.
http://developer.android.com/reference/android/appwidget/AppWidgetProviderInfo.html#resizeMode 
This is especially critical for the Galaxy Note because it uses an uncommon 5x5 grid.

**Comment by kimalec** [comment]
모양 재조정은 신규이슈로 진행하겠습니다.
